name: Conan Build
on:
  push:
    branches:
      - master
      - release-*
      - feat-*

env:
  QT_VERSION_MAJOR: 5
  QT_VERSION_MINOR: 14
  QT_VERSION_PATCH: 1
  QT_VERSION: 5.14.1

jobs:
  
  build_linux:
    name: Linux
    runs-on: ubuntu-16.04
    env:
      QT_INSTALL_TARGET_ARCH: gcc_64
      QT_INSTALL_TARGET_DIR_PREFIX: /opt
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y -qq --no-install-recommends git make cmake g++ wget
          sudo apt-get install -y -qq --no-install-recommends xvfb libgl-dev fcitx fcitx-frontend-qt5
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ env.QT_VERSION }}
          host: linux
          target: desktop
          arch: ${{ env.QT_INSTALL_TARGET_ARCH }}
          dir: ${{ env.QT_INSTALL_TARGET_DIR_PREFIX }}
          modules: qtwebengine
      - name: Download deploy tool
        run: |
          sudo wget -q -O /usr/bin/linuxdeployqt https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
          sudo chmod a+x /usr/bin/linuxdeployqt
      - name: Install and config conan
        run: |
          pip install conan
          conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
          conan remote add conan-community https://api.bintray.com/conan/conan-community/conan
          conan remote add wiznoteplus https://api.bintray.com/conan/altairwei/conan
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default
      - name: Build project
        env:
          QT_INSTALL_PREFIX: ${{ env.QT_INSTALL_TARGET_DIR_PREFIX }}/Qt/${{ env.QT_VERSION }}/${{ env.QT_INSTALL_TARGET_ARCH }}
        run: |
          mkdir -p _build
          ./.ci/build.sh $(pwd) $(pwd)/_build
      - uses: actions/upload-artifact@v1
        with:
          name: Linux_Dist
          path: _build/package/dist
      - name: Upload to Baidu Netdisk
        run: |
          wget https://github.com/iikira/BaiduPCS-Go/releases/download/v3.6.1/BaiduPCS-Go-v3.6.1-linux-amd64.zip
          sudo unzip -j BaiduPCS-Go-v3.6.1-linux-amd64.zip BaiduPCS-Go-v3.6.1-linux-amd64/BaiduPCS-Go -d /usr/bin
          sudo chmod a+x /usr/bin/BaiduPCS-Go
          BaiduPCS-Go login -bduss=${{ secrets.BDUSS }}
          BaiduPCS-Go config set -user_agent="netdisk;1.0"
          BaiduPCS-Go upload $(pwd)/_build/package/dist/WizNotePlus-*.AppImage /我的软件/WizNotePlus/testing


  build_windows:
    name: Windows
    runs-on: windows-2016
    env:
      QT_INSTALL_TARGET_ARCH: msvc2017_64
      QT_INSTALL_TARGET_DIR_PREFIX: "C:"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install dependencies
        shell: powershell
        run: |
          choco install wget unzip
          remove-item alias:wget
      - name: Install and config conan
        shell: powershell
        run: |
          python -m pip install conan
          conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
          conan remote add conan-community https://api.bintray.com/conan/conan-community/conan
          conan remote add wiznoteplus https://api.bintray.com/conan/altairwei/conan
          conan profile new default --detect
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ env.QT_VERSION }}
          host: windows
          target: desktop
          arch: win64_${{ env.QT_INSTALL_TARGET_ARCH }}
          dir: ${{ env.QT_INSTALL_TARGET_DIR_PREFIX }}
          modules: qtwebengine
      - name: Build project
        env:
          QT_INSTALL_PREFIX: ${{ env.QT_INSTALL_TARGET_DIR_PREFIX }}\Qt\${{ env.QT_VERSION }}\${{ env.QT_INSTALL_TARGET_ARCH }}
        shell: powershell
        run: |
          mkdir -Force _build
          .\.ci\build.ps1 "$PWD" "$PWD\_build"
      - uses: actions/upload-artifact@v1
        with:
          name: Windows_Dist
          path: _build/package/dist
      - name: Upload to Baidu Netdisk
        run: |
          wget https://github.com/iikira/BaiduPCS-Go/releases/download/v3.6.1/BaiduPCS-Go-v3.6.1-windows-x64.zip
          unzip -j BaiduPCS-Go-v3.6.1-windows-x64.zip BaiduPCS-Go-v3.6.1-windows-x64/BaiduPCS-Go.exe -d .\
          .\BaiduPCS-Go.exe login -bduss=${{ secrets.BDUSS }}
          .\BaiduPCS-Go.exe config set -user_agent="netdisk;1.0"
          .\BaiduPCS-Go.exe upload (get-item "$PWD\_build\package\dist\WizNotePlus-*.zip") /我的软件/WizNotePlus/testing

  build_macos:
    name: MacOS
    runs-on: macos-latest
    env:
      QT_INSTALL_TARGET_ARCH: clang_64
      QT_INSTALL_TARGET_DIR_PREFIX: "/Applications"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install dependencies
        run: |
          sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}
          npm install --global appdmg
          brew install unzip
      - name: Install and config conan
        run: |
          python -m pip install conan
          conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
          conan remote add conan-community https://api.bintray.com/conan/conan-community/conan
          conan remote add wiznoteplus https://api.bintray.com/conan/altairwei/conan
          conan profile new default --detect
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ env.QT_VERSION }}
          host: mac
          target: desktop
          arch: ${{ env.QT_INSTALL_TARGET_ARCH }}
          dir: ${{ env.QT_INSTALL_TARGET_DIR_PREFIX }}
          modules: qtwebengine
      - name: Build project
        env:
          QT_INSTALL_PREFIX: ${{ env.QT_INSTALL_TARGET_DIR_PREFIX }}/Qt/${{ env.QT_VERSION }}/${{ env.QT_INSTALL_TARGET_ARCH }}
        run: |
          mkdir -p _build
          ./.ci/build.sh $(pwd) $(pwd)/_build
      - uses: actions/upload-artifact@v1
        with:
          name: MacOS_Dist
          path: _build/package/dist
      - name: Upload to Baidu Netdisk
        run: |
          wget https://github.com/iikira/BaiduPCS-Go/releases/download/v3.6.1/BaiduPCS-Go-v3.6.1-darwin-osx-amd64.zip
          unzip -j BaiduPCS-Go-v3.6.1-darwin-osx-amd64.zip BaiduPCS-Go-v3.6.1-darwin-osx-amd64/BaiduPCS-Go -d ./
          sudo chmod a+x ./BaiduPCS-Go
          ./BaiduPCS-Go login -bduss=${{ secrets.BDUSS }}
          ./BaiduPCS-Go config set -user_agent="netdisk;1.0"
          ./BaiduPCS-Go upload $(pwd)/_build/package/dist/WizNotePlus-*.dmg /我的软件/WizNotePlus/testing